name: Build and deploy test system

on:
  push:
    branches: 
      - "testbranch"
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo "sandevdsic123" | sudo -S sudo docker build . --file Dockerfile --tag notification-service-testbranch-image:latest
    - name: stop current system
      run: echo "sandevdsic123" | sudo -S sudo docker compose down
    - name: Execute dokcer compose file
      run: echo "sandevdsic123" | sudo -S sudo docker compose up -d
